---
- name: Printing survey variables from AWX tower
  gather_facts: false
  hosts: all
  tasks:
    - debug:
        var: var1
    - debug:
        var: var2
    - debug:
        var: var3[1]
    - debug:
        msg: "End of playbook"
